### ISSUE TITLE
不能登陆我的arm开发版

### ISSUE THREAD

**Issue by 652436962** [thb1314/HaibinSerialPortDebuger#2]
Welcome to X
[收] 2020-11-23 22:48:15 607
6818
tarena login: 
[发] 2020-11-23 22:48:22 660
root
[收] 2020-11-23 22:48:22 66

**Comment by 652436962** [comment]
而且好像没接受完，显示的信息好少

**Comment by thb1314** [comment]
> 

是不是波特率校验位之类的设置错了呀？
