### ISSUE TITLE
串口助手界面的颜色该怎么修改呢？

### ISSUE THREAD

**Issue by SDsdfasfcsd** [thb1314/HaibinSerialPortDebuger#3]
作者您好，我想请教您一个问题：串口助手界面的颜色该怎么修改呢？我尝试修改config.h中颜色的定义数值#F0F0F0但是不起作用，希望作者给予指点

**Comment by thb1314** [comment]
> 

使用qss修改试试

**Comment by thb1314** [comment]
> 作者您好，我想请教您一个问题：串口助手界面的颜色该怎么修改呢？我尝试修改config.h中颜色的定义数值#F0F0F0但是不起作用，希望作者给予指点

使用qss修改试试
